version: '3'

services:
  db:
    image: postgres
    restart: always
    tty: true
    volumes:
    - .pgdata:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=pgdb
    ports:
    - "5432:5432"
